/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_teamdeadbolts_amd_AmdJNI */

#ifndef _Included_org_teamdeadbolts_amd_AmdJNI
#define _Included_org_teamdeadbolts_amd_AmdJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_teamdeadbolts_amd_AmdJNI
 * Method:    create
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_org_teamdeadbolts_amd_AmdJNI_create
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     org_teamdeadbolts_amd_AmdJNI
 * Method:    setDevice
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_teamdeadbolts_amd_AmdJNI_setDevice
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_teamdeadbolts_amd_AmdJNI
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_teamdeadbolts_amd_AmdJNI_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_amd_AmdJNI
 * Method:    detect
 * Signature: (JJDD)[Lorg/teamdeadbolts/amd/AmdJNI/AmdResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_teamdeadbolts_amd_AmdJNI_detect
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble);

/*
 * Class:     org_teamdeadbolts_amd_AmdJNI
 * Method:    isQuantized
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_teamdeadbolts_amd_AmdJNI_isQuantized
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
