name: Publish Package

on:
  release:
    types: [created]
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # This gives GITHUB_TOKEN write access
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
      
      - name: Publish to GitHub Packages
        run: mkdir cmake_build && ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          GITHUB_ACTOR: ${{ github.actor }}   