name: Publish Package

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # This gives GITHUB_TOKEN write access
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
      
      - name: Build natives
        run: |
          mkdir -p cmake_build
          cd cmake_build
          cmake ..
          cmake --build .
      
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          GITHUB_ACTOR: ${{ github.actor }}   